# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Slack PR notification
on:
  pull_request:
    types:
      - opened
      - reopened
      - closed

jobs:
  notify:
    name: Send Slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Checkout the repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Forward a saved message
        uses: slackapi/slack-github-action@v4.0.0
        with:
          payload-file-path: "./.github/workflows/slack/pr_opened.json"
          payload-templated: true
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook